# Generated by Django 3.0.8 on 2020-09-16 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dino',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fun_pun', models.TextField(max_length=350)),
                ('description', models.TextField(max_length=250)),
            ],
        ),
    ]
