# Generated by Django 3.0.8 on 2020-09-16 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sighting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('location', models.CharField(choices=[('H', 'Horizon'), ('B', 'Backyard'), ('P', 'From a Plane')], default='H', max_length=1)),
                ('dino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Dino')),
            ],
        ),
    ]
